# Generated by Django 5.1.2 on 2024-11-27 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Image', models.ImageField(upload_to='image/')),
                ('CategoryType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
    ]
