# Generated by Django 5.1.2 on 2024-11-29 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_shiptype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=30)),
                ('Quentity', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('TotalPrice', models.IntegerField()),
                ('OrderDate', models.CharField(max_length=30)),
                ('DeliverData', models.CharField(max_length=30)),
                ('DeliveryStatus', models.CharField(max_length=30, null=True)),
                ('Customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shiptype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shiptype')),
            ],
        ),
    ]
