# Generated by Django 5.1.2 on 2024-11-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='OrderID',
            field=models.IntegerField(null=True),
        ),
    ]
