# Generated by Django 5.1.2 on 2024-11-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_buy_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='OrderID',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
