# Generated by Django 5.1.2 on 2024-11-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_buy_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='PaymentMethod',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='DeliveryStatus',
            field=models.CharField(default='Pending', max_length=30, null=True),
        ),
    ]
