# Generated by Django 5.1.2 on 2024-11-30 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_buy_paymentmethod_alter_buy_deliverystatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeliveryAgent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('OrderList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.buy')),
            ],
        ),
    ]
