# Generated by Django 5.1.2 on 2024-11-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_buy_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='DeliveryCondition',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
