# Generated by Django 5.1.2 on 2024-12-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_buy_deliverycondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='Loaction',
            field=models.CharField(default='Location Not Update', max_length=30, null=True),
        ),
    ]
