# Generated by Django 5.1.2 on 2024-12-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_buy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='Image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
