# Generated by Django 5.1.2 on 2024-12-10 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_buy_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='Image',
            new_name='Image1',
        ),
    ]
