# Generated by Django 5.1.2 on 2024-12-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_image_buy_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttable',
            name='Specifications',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
