# Generated by Django 5.1.2 on 2024-12-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_buy_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='Description',
            field=models.CharField(max_length=150),
        ),
    ]
