# Generated by Django 5.1.2 on 2024-12-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_buy_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='Specifications',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
