# Generated by Django 5.1.2 on 2024-12-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_buy_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='status',
            field=models.CharField(choices=[('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='Current Status Not Updated', max_length=50, null=True),
        ),
    ]
